local icons = {
    check = "",
    note = "",
    flame = "",
    debug = "",
    trace = "",
    test = "󰙨",
    lock = "",
    modified = "",
    file = "󰈚",
    --[[ border = {
		"┌",
		"─",
		"┐",
		"│",
		"┘",
		"─",
		"└",
		"│",
	}, ]]
    diagnostics = {
        info = " ",
        hint = " ",
        warn = " ",
        error = " ",
    },
    fold = {
        open = "",
        close = "",
    },
    diff = {
        added = "",
        modified = "",
        removed = "",
    },
    git = {
        added = "",
        modified = "",
        deleted = "",
        renamed = "󰁕",
        untracked = "",
        ignored = "",
        unstaged = "󰄱",
        staged = "",
        conflict = "",
    },
    folder = {
        -- open = "",
        -- close = "",
        empty = "󰜌",

        open = "",
        close = "",
        empty_open = "",
        symlink = "",
        symlink_open = "",
    },
    kind = {
        Class = "󱡠",
        Color = "󰏘",
        Constant = "󰏿",
        Constructor = "󰒓",
        Enum = "󰦨",
        EnumMember = "󰦨",
        Event = "󱐋",
        Field = "󰜢",
        File = "󰈔",
        Folder = "󰉋",
        Function = "󰊕",
        Interface = "󱡠",
        Keyword = "󰻾",
        Method = "󰊕",
        Module = "󰅩",
        Operator = "󰪚",
        Property = "󰖷",
        Reference = "󰬲",
        Snippet = "󱄽",
        Struct = "󱡠",
        Text = "󰉿",
        TypeParameter = "󰬛",
        Unit = "󰪚",
        Value = "󰦨",
        Variable = "󰆦",
    },
}

return icons
--[[

Class = " ",
Constant = "󰏿 ",
Constructor = " ",
Enum = " ",
EnumMember = " ",
Event = " ",
Field = " ",
File = " ",
Function = "󰊕 ",
Interface = " ",
Key = " ",
Method = "󰊕 ",
Module = " ",
Namespace = "󰦮 ",
Null = " ",
Number = "󰎠 ",
Object = " ",
Operator = " ",
Package = " ",
Property = " ",
String = " ",
Struct = "󰆼 ",
TypeParameter = " ",
Variable = "󰀫 ", 

-- NEW --
Array = " ",
-- Boolean = " ",
Boolean = "󰨙 ",
Class = " ",
Color = " ",
Constant = " ",
Constructor = " ",
Enum = " ",
EnumMember = " ",
Event = " ",
Field = " ",
File = " ",
Folder = " ",
Function = " ",
Interface = " ",
Key = "󰉿 ",
Keyword = " ",
Method = " ",
Module = " ",
Namespace = " ",
Null = " ",
Number = " ",
Object = " ",
Operator = " ",
Package = " ",
Property = " ",
Reference = " ",
Snippet = " ",
String = " ",
Struct = " ",
Text = "󰉿 ",
TypeParameter = "󰊄 ",
Unit = " ",
Value = "󰉿 ",
Variable = " ",

]]
